// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Guard: detectar configuración incorrecta antes de que cause errores silenciosos.
// Si VITE_SUPABASE_URL no está definida o apunta al proyecto interno de Lovable,
// lanzamos un error claro en consola para facilitar el diagnóstico.
if (!SUPABASE_URL || SUPABASE_URL.includes('bqcktccunwqgpsgejwhy')) {
  console.error(
    '[Kairo] VITE_SUPABASE_URL está vacía o apunta al proyecto incorrecto.\n' +
    'Verifica que en Vercel (Frontend > Settings > Environment Variables)\n' +
    'VITE_SUPABASE_URL = https://wyywukatjjksaetvoekg.supabase.co\n' +
    'y luego haz Redeploy.'
  );
}

// Si por error Vercel sigue inyectando la URL vieja de Lovable, la reemplazamos a la fuerza
const finalSupabaseUrl = (!SUPABASE_URL || SUPABASE_URL.includes('bqcktccunwqgpsgejwhy')) 
  ? 'https://wyywukatjjksaetvoekg.supabase.co' 
  : SUPABASE_URL;

export const supabase = createClient<Database>(
  finalSupabaseUrl,
  SUPABASE_PUBLISHABLE_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);